# Generated by Django 5.2.5 on 2025-08-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_created_at_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
    ]
