# Generated by Django 5.2.5 on 2025-08-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Categories/'),
        ),
    ]
